version: "3.7"
services:
  pycharm:
    image: pycharm-c:23.01.26
    ports:
      - "8888:8888"
    volumes:
      - ./plugins:/tmp/plugins
    #  - ./work:/home/dev/app/
    #  - app-cache:/home/dev/.gradle/:rw
    # https://qiita.com/m-shimao/items/d420c1773ecf5fbaabdf
    environment:
      - NB_USER=$NB_USER
      - NB_GROUP=$NB_USER
      - NB_UID=$NB_UID
      - NB_GID=$NB_UID
      - CHOWN_HOME=yes
    working_dir: /home/$NB_USER/work
    environment:
      - JAVA_OPTS=-server -Xms1024M -Xmx1024M -XX:MetaspaceSize=128m -Xss3m
    # tty: true
    # command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
    command: ["jupyter", "lab", "--no-browser", "--port", "8888", "--ip=*", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
volumes:
  app-cache: