version: "3.7"
services:
  pycharm:
    image: pycharm-c:23.01.26
    ports:
      - "8888:8888"
    working_dir: /home/$NB_USER/work
    environment:
      - JAVA_OPTS=-server -Xms1024M -Xmx1024M -XX:MetaspaceSize=128m -Xss3m
    command: ["jupyter", "lab", "--no-browser", "--port", "8888", "--ip=*", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
volumes:
  app-cache: